// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: audio.proto
#ifndef GRPC_audio_2eproto__INCLUDED
#define GRPC_audio_2eproto__INCLUDED

#include "audio.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace rero {

class AudioStreamer final {
 public:
  static constexpr char const* service_full_name() {
    return "rero.AudioStreamer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    std::unique_ptr< ::grpc::ClientReaderInterface< ::rero::Audio>> GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::rero::Audio>>(GetStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rero::Audio>> AsyncGetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rero::Audio>>(AsyncGetStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rero::Audio>> PrepareAsyncGetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rero::Audio>>(PrepareAsyncGetStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>> PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>>(PlayAudioRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> AsyncPlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(AsyncPlayAudioRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> PrepareAsyncPlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(PrepareAsyncPlayAudioRaw(context, response, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest* request, ::grpc::ClientReadReactor< ::rero::Audio>* reactor) = 0;
      #else
      virtual void GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::rero::Audio>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #else
      virtual void PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::rero::Audio>* GetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rero::Audio>* AsyncGetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rero::Audio>* PrepareAsyncGetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::rero::Audio>* PlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* AsyncPlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* PrepareAsyncPlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::rero::Audio>> GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::rero::Audio>>(GetStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rero::Audio>> AsyncGetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rero::Audio>>(AsyncGetStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rero::Audio>> PrepareAsyncGetStream(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rero::Audio>>(PrepareAsyncGetStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>> PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>>(PlayAudioRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> AsyncPlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(AsyncPlayAudioRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> PrepareAsyncPlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(PrepareAsyncPlayAudioRaw(context, response, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest* request, ::grpc::ClientReadReactor< ::rero::Audio>* reactor) override;
      #else
      void GetStream(::grpc::ClientContext* context, const ::rero::StreamRequest* request, ::grpc::experimental::ClientReadReactor< ::rero::Audio>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #else
      void PlayAudio(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::rero::Audio>* GetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::rero::Audio>* AsyncGetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::rero::Audio>* PrepareAsyncGetStreamRaw(::grpc::ClientContext* context, const ::rero::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::rero::Audio>* PlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* AsyncPlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* PrepareAsyncPlayAudioRaw(::grpc::ClientContext* context, ::rero::PlayResult* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetStream_;
    const ::grpc::internal::RpcMethod rpcmethod_PlayAudio_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status GetStream(::grpc::ServerContext* context, const ::rero::StreamRequest* request, ::grpc::ServerWriter< ::rero::Audio>* writer);
    virtual ::grpc::Status PlayAudio(::grpc::ServerContext* context, ::grpc::ServerReader< ::rero::Audio>* reader, ::rero::PlayResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStream(::grpc::ServerContext* context, ::rero::StreamRequest* request, ::grpc::ServerAsyncWriter< ::rero::Audio>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PlayAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PlayAudio() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PlayAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::PlayResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlayAudio(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::rero::PlayResult, ::rero::Audio>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetStream<WithAsyncMethod_PlayAudio<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::rero::StreamRequest, ::rero::Audio>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::rero::StreamRequest* request) { return this->GetStream(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::rero::Audio>* GetStream(
      ::grpc::CallbackServerContext* /*context*/, const ::rero::StreamRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::rero::Audio>* GetStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::rero::StreamRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PlayAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PlayAudio() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::rero::Audio, ::rero::PlayResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::rero::PlayResult* response) { return this->PlayAudio(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_PlayAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::PlayResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::rero::Audio>* PlayAudio(
      ::grpc::CallbackServerContext* /*context*/, ::rero::PlayResult* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::rero::Audio>* PlayAudio(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::rero::PlayResult* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetStream<ExperimentalWithCallbackMethod_PlayAudio<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetStream<ExperimentalWithCallbackMethod_PlayAudio<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PlayAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PlayAudio() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PlayAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::PlayResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PlayAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PlayAudio() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PlayAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::PlayResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlayAudio(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->GetStream(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* GetStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PlayAudio : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PlayAudio() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->PlayAudio(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PlayAudio() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayAudio(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::PlayResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* PlayAudio(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* PlayAudio(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::rero::StreamRequest, ::rero::Audio>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::rero::StreamRequest, ::rero::Audio>* streamer) {
                       return this->StreamedGetStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStream(::grpc::ServerContext* /*context*/, const ::rero::StreamRequest* /*request*/, ::grpc::ServerWriter< ::rero::Audio>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::rero::StreamRequest,::rero::Audio>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetStream<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetStream<Service > StreamedService;
};

}  // namespace rero


#endif  // GRPC_audio_2eproto__INCLUDED
