// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hotword.proto
#ifndef GRPC_hotword_2eproto__INCLUDED
#define GRPC_hotword_2eproto__INCLUDED

#include "hotword.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace rero {

class HotwordDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "rero.HotwordDetection";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>> StartHotwordStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>>(StartHotwordStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>> AsyncStartHotwordStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>>(AsyncStartHotwordStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>> PrepareAsyncStartHotwordStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>>(PrepareAsyncStartHotwordStreamRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>> RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>>(RecognizeHotwordRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> AsyncRecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(AsyncRecognizeHotwordRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> PrepareAsyncRecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(PrepareAsyncRecognizeHotwordRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>> GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::rero::Audio>>(GetEmbeddingRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> AsyncGetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(AsyncGetEmbeddingRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>> PrepareAsyncGetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::rero::Audio>>(PrepareAsyncGetEmbeddingRaw(context, response, cq));
    }
    virtual ::grpc::Status AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::rero::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>> AsyncAddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>>(AsyncAddEmbeddingToHotwordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>> PrepareAsyncAddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>>(PrepareAsyncAddEmbeddingToHotwordRaw(context, request, cq));
    }
    virtual ::grpc::Status PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::rero::Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>> AsyncPersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>>(AsyncPersistHotwordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>> PrepareAsyncPersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>>(PrepareAsyncPersistHotwordRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StartHotwordStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::rero::Audio,::rero::HotwordResult>* reactor) = 0;
      #else
      virtual void StartHotwordStream(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::rero::Audio,::rero::HotwordResult>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #else
      virtual void RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #else
      virtual void GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) = 0;
      #endif
      virtual void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>* StartHotwordStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>* AsyncStartHotwordStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::rero::Audio, ::rero::HotwordResult>* PrepareAsyncStartHotwordStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::rero::Audio>* RecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* AsyncRecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* PrepareAsyncRecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::rero::Audio>* GetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* AsyncGetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::rero::Audio>* PrepareAsyncGetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>* AsyncAddEmbeddingToHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>* PrepareAsyncAddEmbeddingToHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>* AsyncPersistHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rero::Result>* PrepareAsyncPersistHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::rero::Audio, ::rero::HotwordResult>> StartHotwordStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::rero::Audio, ::rero::HotwordResult>>(StartHotwordStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>> AsyncStartHotwordStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>>(AsyncStartHotwordStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>> PrepareAsyncStartHotwordStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>>(PrepareAsyncStartHotwordStreamRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>> RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>>(RecognizeHotwordRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> AsyncRecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(AsyncRecognizeHotwordRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> PrepareAsyncRecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(PrepareAsyncRecognizeHotwordRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>> GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::rero::Audio>>(GetEmbeddingRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> AsyncGetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(AsyncGetEmbeddingRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>> PrepareAsyncGetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::rero::Audio>>(PrepareAsyncGetEmbeddingRaw(context, response, cq));
    }
    ::grpc::Status AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::rero::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>> AsyncAddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>>(AsyncAddEmbeddingToHotwordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>> PrepareAsyncAddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>>(PrepareAsyncAddEmbeddingToHotwordRaw(context, request, cq));
    }
    ::grpc::Status PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::rero::Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>> AsyncPersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>>(AsyncPersistHotwordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>> PrepareAsyncPersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rero::Result>>(PrepareAsyncPersistHotwordRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StartHotwordStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::rero::Audio,::rero::HotwordResult>* reactor) override;
      #else
      void StartHotwordStream(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::rero::Audio,::rero::HotwordResult>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #else
      void RecognizeHotword(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #else
      void GetEmbedding(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::experimental::ClientWriteReactor< ::rero::Audio>* reactor) override;
      #endif
      void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void AddEmbeddingToHotword(::grpc::ClientContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PersistHotword(::grpc::ClientContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::rero::Audio, ::rero::HotwordResult>* StartHotwordStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>* AsyncStartHotwordStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::rero::Audio, ::rero::HotwordResult>* PrepareAsyncStartHotwordStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::rero::Audio>* RecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* AsyncRecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* PrepareAsyncRecognizeHotwordRaw(::grpc::ClientContext* context, ::rero::HotwordResult* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::rero::Audio>* GetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* AsyncGetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::rero::Audio>* PrepareAsyncGetEmbeddingRaw(::grpc::ClientContext* context, ::rero::RawEmbedding* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rero::Result>* AsyncAddEmbeddingToHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rero::Result>* PrepareAsyncAddEmbeddingToHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordEmbedding& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rero::Result>* AsyncPersistHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rero::Result>* PrepareAsyncPersistHotwordRaw(::grpc::ClientContext* context, const ::rero::HotwordFileName& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartHotwordStream_;
    const ::grpc::internal::RpcMethod rpcmethod_RecognizeHotword_;
    const ::grpc::internal::RpcMethod rpcmethod_GetEmbedding_;
    const ::grpc::internal::RpcMethod rpcmethod_AddEmbeddingToHotword_;
    const ::grpc::internal::RpcMethod rpcmethod_PersistHotword_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StartHotwordStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* stream);
    virtual ::grpc::Status RecognizeHotword(::grpc::ServerContext* context, ::grpc::ServerReader< ::rero::Audio>* reader, ::rero::HotwordResult* response);
    virtual ::grpc::Status GetEmbedding(::grpc::ServerContext* context, ::grpc::ServerReader< ::rero::Audio>* reader, ::rero::RawEmbedding* response);
    virtual ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* context, const ::rero::HotwordEmbedding* request, ::rero::Result* response);
    virtual ::grpc::Status PersistHotword(::grpc::ServerContext* context, const ::rero::HotwordFileName* request, ::rero::Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartHotwordStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartHotwordStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartHotwordStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartHotwordStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartHotwordStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::rero::HotwordResult, ::rero::Audio>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecognizeHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecognizeHotword() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RecognizeHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeHotword(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::HotwordResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeHotword(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::rero::HotwordResult, ::rero::Audio>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEmbedding() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmbedding(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::RawEmbedding* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEmbedding(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::rero::RawEmbedding, ::rero::Audio>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddEmbeddingToHotword() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddEmbeddingToHotword(::grpc::ServerContext* context, ::rero::HotwordEmbedding* request, ::grpc::ServerAsyncResponseWriter< ::rero::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PersistHotword() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPersistHotword(::grpc::ServerContext* context, ::rero::HotwordFileName* request, ::grpc::ServerAsyncResponseWriter< ::rero::Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartHotwordStream<WithAsyncMethod_RecognizeHotword<WithAsyncMethod_GetEmbedding<WithAsyncMethod_AddEmbeddingToHotword<WithAsyncMethod_PersistHotword<Service > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StartHotwordStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StartHotwordStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::rero::Audio, ::rero::HotwordResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StartHotwordStream(context); }));
    }
    ~ExperimentalWithCallbackMethod_StartHotwordStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartHotwordStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::rero::Audio, ::rero::HotwordResult>* StartHotwordStream(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::rero::Audio, ::rero::HotwordResult>* StartHotwordStream(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RecognizeHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RecognizeHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::rero::Audio, ::rero::HotwordResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::rero::HotwordResult* response) { return this->RecognizeHotword(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_RecognizeHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeHotword(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::HotwordResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::rero::Audio>* RecognizeHotword(
      ::grpc::CallbackServerContext* /*context*/, ::rero::HotwordResult* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::rero::Audio>* RecognizeHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::rero::HotwordResult* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetEmbedding() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::rero::Audio, ::rero::RawEmbedding>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::rero::RawEmbedding* response) { return this->GetEmbedding(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_GetEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmbedding(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::RawEmbedding* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::rero::Audio>* GetEmbedding(
      ::grpc::CallbackServerContext* /*context*/, ::rero::RawEmbedding* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::rero::Audio>* GetEmbedding(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::rero::RawEmbedding* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_AddEmbeddingToHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::rero::HotwordEmbedding, ::rero::Result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::rero::HotwordEmbedding* request, ::rero::Result* response) { return this->AddEmbeddingToHotword(context, request, response); }));}
    void SetMessageAllocatorFor_AddEmbeddingToHotword(
        ::grpc::experimental::MessageAllocator< ::rero::HotwordEmbedding, ::rero::Result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rero::HotwordEmbedding, ::rero::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AddEmbeddingToHotword(
      ::grpc::CallbackServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AddEmbeddingToHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PersistHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::rero::HotwordFileName, ::rero::Result>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::rero::HotwordFileName* request, ::rero::Result* response) { return this->PersistHotword(context, request, response); }));}
    void SetMessageAllocatorFor_PersistHotword(
        ::grpc::experimental::MessageAllocator< ::rero::HotwordFileName, ::rero::Result>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(4);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rero::HotwordFileName, ::rero::Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PersistHotword(
      ::grpc::CallbackServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PersistHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StartHotwordStream<ExperimentalWithCallbackMethod_RecognizeHotword<ExperimentalWithCallbackMethod_GetEmbedding<ExperimentalWithCallbackMethod_AddEmbeddingToHotword<ExperimentalWithCallbackMethod_PersistHotword<Service > > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StartHotwordStream<ExperimentalWithCallbackMethod_RecognizeHotword<ExperimentalWithCallbackMethod_GetEmbedding<ExperimentalWithCallbackMethod_AddEmbeddingToHotword<ExperimentalWithCallbackMethod_PersistHotword<Service > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartHotwordStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartHotwordStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartHotwordStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartHotwordStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecognizeHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecognizeHotword() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RecognizeHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeHotword(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::HotwordResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEmbedding() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmbedding(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::RawEmbedding* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddEmbeddingToHotword() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PersistHotword() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartHotwordStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartHotwordStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartHotwordStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartHotwordStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartHotwordStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecognizeHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecognizeHotword() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RecognizeHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeHotword(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::HotwordResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeHotword(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEmbedding() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmbedding(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::RawEmbedding* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEmbedding(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddEmbeddingToHotword() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddEmbeddingToHotword(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PersistHotword() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPersistHotword(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StartHotwordStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StartHotwordStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StartHotwordStream(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_StartHotwordStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartHotwordStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::rero::HotwordResult, ::rero::Audio>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StartHotwordStream(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StartHotwordStream(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RecognizeHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RecognizeHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->RecognizeHotword(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RecognizeHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeHotword(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::HotwordResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* RecognizeHotword(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* RecognizeHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetEmbedding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetEmbedding() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->GetEmbedding(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetEmbedding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmbedding(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::rero::Audio>* /*reader*/, ::rero::RawEmbedding* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* GetEmbedding(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* GetEmbedding(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_AddEmbeddingToHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddEmbeddingToHotword(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* AddEmbeddingToHotword(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* AddEmbeddingToHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PersistHotword() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PersistHotword(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PersistHotword(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PersistHotword(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddEmbeddingToHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddEmbeddingToHotword() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rero::HotwordEmbedding, ::rero::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rero::HotwordEmbedding, ::rero::Result>* streamer) {
                       return this->StreamedAddEmbeddingToHotword(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddEmbeddingToHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddEmbeddingToHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordEmbedding* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddEmbeddingToHotword(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rero::HotwordEmbedding,::rero::Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PersistHotword : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PersistHotword() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rero::HotwordFileName, ::rero::Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rero::HotwordFileName, ::rero::Result>* streamer) {
                       return this->StreamedPersistHotword(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PersistHotword() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PersistHotword(::grpc::ServerContext* /*context*/, const ::rero::HotwordFileName* /*request*/, ::rero::Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPersistHotword(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rero::HotwordFileName,::rero::Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddEmbeddingToHotword<WithStreamedUnaryMethod_PersistHotword<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddEmbeddingToHotword<WithStreamedUnaryMethod_PersistHotword<Service > > StreamedService;
};

}  // namespace rero


#endif  // GRPC_hotword_2eproto__INCLUDED
